
services:
  - type: web
    name: tagcon-backend
    runtime: node
    root: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://jmurenguko:5KKBBr6O3ye0xZUi@cluster0.3iilu.mongodb.net/tagcon?retryWrites=true&w=majority&appName=Cluster0
      - key: PORT
        value: 3000

  - type: web
    name: tagcon-frontend
    runtime: static
    root: frontend
    buildCommand: npm install && npm run build
    staticPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://tagcon-backend.onrender.com